### ISSUE TITLE
Site language selection (UK)

### ISSUE THREAD

**Issue by PointandStare** [ClassicPress/ClassicPress#347] opened 2019-01-28 17:50 UTC
## Expected behavior
Language option for UK version of English should be listed as English (UK)

## Current behavior
Currently listed as en_GB

## Possible solution
Change the option to English (UK)

## Steps to reproduce (for bugs)
1. Settings > General > Site Language
2. Choose languages from the dropdown

## Context
I'm traumatised with the struggle to get the world to accept 'real' English ...

**Comment by Mte90** [comment] 2019-01-28 18:18
can you share a screen? because we are using the same wording of WordPress

**Comment by PointandStare** [comment] 2019-01-29 10:52
CP v: ClassicPress 1.0.0-beta2+migration.20181220
Plugins, nothing to worry about as this is just a test install, so sometimes nothing, sometimes a few - WordFence etc.

**Comment by PointandStare** [comment] 2019-01-29 10:53
Oh, and this was migrated from WP 5.0 a few weeks ago so might be needing an update BUT, there's nothing stating so.

**Comment by Mte90** [comment] 2019-01-29 10:58
Probably you had that language before the migration and now that is missing is not in the list?

Anyway can you do a screenshot of the list of your locales? just to understand if the problem is that is missing or it is showing something else?

We want to support English (UK) and probably the endpoint are not generating for UK because there was never new string approved after our import so cannot do the check for a previous version and adding on the list.
I did that on few strings, let's see in the next hour our endpoint.

**Comment by PointandStare** [comment] 2019-01-29 11:05
![screen shot 2019-01-29 at 11 02 33](https://user-images.githubusercontent.com/962273/51904086-acffaa80-23b5-11e9-80bc-6f2fdc7082b3.png)
Same as I posted on Slack.
No translation/ WPML/ Polylang etc used in this install.

**Comment by Mte90** [comment] 2019-01-29 11:26
The problem is that the en-gb locales in ClassicPress doesn't have our threshold of localized strings to be avalaible .
We are requiring 95% and after few review it is as 94% (before was 86%).
When will be at that percentage you will have the right name in the UI.

**Comment by Mte90** [comment] 2019-01-29 11:32
Now the english language has the 95% percentage so our automatic system in the next 4 hours will update the list and this will be fixed in your instance.

**Comment by nylen** [comment] 2019-01-29 18:51
> @PointandStare how did you get this en_GB language installed?

I haven't seen an answer to this question.

**Comment by Zealth57** [comment] 2019-01-29 18:55
@nylen he migrated it from an existing WP install. If you install WP or switch you language when using WP and then migrate over with that language pack selected, it will do what he did. I verified this by installing the latest version of WP locally, selecting English (UK) during install, then using the migrate plugin.

**Comment by nylen** [comment] 2019-01-29 20:14
Ok, thanks @Zealth57!

Just to confirm, have you tested this again today with `en_GB` after the changes we made on the server?

I think we will have the same problem with other languages, but we can move that to a separate issue after we finish this one.

**Comment by Zealth57** [comment] 2019-01-29 20:20
I tested just now, and it's properly showing English (UK) instead of the language code it previously did. I would consider this closed.

It's probably best to address the overarching issue with this: https://github.com/ClassicPress/ClassicPress-Migration-Plugin/issues/18 on the migrate plugin. Maybe a yellow caution icon and warning letting them know their current locale isn't supported yet?

**Closed** 2019-01-29 21:22 UTC
Labels: bug, i18n

**Comment by PointandStare** [comment] 2019-01-30 09:12
Apologies for not getting back.

As mentioned, fresh WP install set to English (UK) which was then migrated to CP (I wanted to test the migration).
