### ISSUE TITLE
get_the_excerpt() shows warning if post excerpt is empty

### ISSUE THREAD

**Issue by johnalarcon** [ClassicPress/ClassicPress#316] opened 2018-12-22 18:10 UTC
I'm getting the following warning under PHP 7.2.3 when using `get_the_excerpt()` on a post that has an empty excerpt. 

> Warning: count(): Parameter must be an array or an object that implements Countable in C:\xampp\htdocs\ClassicPress\wp-includes\post-template.php on line 284

## Possible solution
In `./wp-includes/post-template.php`, add an additional check...

```
function get_the_excerpt( $post = null ) {
	if ( is_bool( $post ) ) {
		_deprecated_argument( __FUNCTION__, 'WP-2.3.0' );
	}

	$post = get_post( $post );
	if ( empty( $post ) ) {
		return '';
	}

	// Additional check.
	if ( empty( $post->excerpt ) ) {
		return '';
	}

	if ( post_password_required( $post ) ) {
		return __( 'There is no excerpt because this is a protected post.' );
	}

	/**
	 * Filters the retrieved post excerpt.
	 *
	 * @since WP-1.2.0
	 * @since WP-4.5.0 Introduced the `$post` parameter.
	 *
	 * @param string $post_excerpt The post excerpt.
	 * @param WP_Post $post Post object.
	 */
	return apply_filters( 'get_the_excerpt', $post->post_excerpt, $post );
}
```

## Steps to reproduce (for bugs)
1. add `$excerpt = get_the_excerpt();` to any theme's header.php file.
2. visit any post that does not have an excerpt

## Context
Working toward PHP 7 compatibility.

**Comment by Mte90** [comment] 2018-12-23 13:43
I think that implement this can break the compatibility with WP itself.
WP doesn't have anything that fix that issue https://github.com/WordPress/WordPress/blob/master/wp-includes/post-template.php#L389
So I am wondering if they did change to the Post objectin wordpress to fix from the top this issue.

**Comment by GTMAN** [comment] 2018-12-27 16:57
[https://core.trac.wordpress.org/ticket/42814](url) seems it keeps getting punted until the next release.

**Comment by Mte90** [comment] 2018-12-27 16:59
Also this patch it is not so tiny and require a lot of changes but seems that they planned for 5.0.3

**Comment by johnalarcon** [comment] 2018-12-27 18:09
Wow, that's a long thread. Thanks for digging deeper into this.

**Comment by nylen** [comment] 2018-12-27 20:08
Also related: https://core.trac.wordpress.org/ticket/36934

**Comment by invisnet** [comment] 2019-01-22 22:59
The problem is in `get_the_content`, not `get_the_excerpt` - if there's no excerpt it grabs the first part of the content and that's when you get the error.

I'll do a PR in a bit - or someone else can - but it's these two lines in `get_the_content` that're the problem:

```
	if ( $page > count( $pages ) ) // if the requested page doesn't exist
		$page = count( $pages ); // give them the highest numbered page that DOES exist
```

I've not tried this, but I'm guessing `$page` defaults to `1`, so:

```
	if ( ! empty( $pages ) && $page > count( $pages ) ) // if the requested page doesn't exist
```

should do the trick.

**Comment by invisnet** [comment] 2019-01-23 09:48
Ignore my previous. The problem is indeed in `get_the_content()`:
```
	if ( $page > count( $pages ) ) // if the requested page doesn't exist
		$page = count( $pages ); // give them the highest numbered page that DOES exist
```
where `$pages` is empty.

The cause of that is not calling `the_post()` first; `$pages` is populated in `WP_Post::setup_postdata()`, and that is _only_ called in `the_post()` and `wp_reset_postdata()`.

The correct solution is a "doing it wrong" if `$pages` is empty.

**Comment by nylen** [comment] 2019-01-24 01:40
> The correct solution is a "doing it wrong" if `$pages` is empty.

This might be the correct solution if starting from scratch, with core functions that all understand how to operate in the context of any post, but doing it now is probably going to break all kinds of stuff.

More specific info, getting to a couple of possible root causes here:

- https://core.trac.wordpress.org/ticket/36934#comment:11
- https://core.trac.wordpress.org/ticket/42814#comment:17

**Comment by nylen** [comment] 2019-01-25 19:08
I've removed this from the v1.0.0 milestone.  I would consider merging a minimal fix for the most common causes of this issue, but we are running out of time both for implementation and review.

In order for something to be merged here, anyone working on this issue will need to make it easy to review, and they will need to do the majority of the work of proving that the fix is correct themselves.  The best way to do this would be to clearly explain the code path that is followed in order to see this issue, and also use **test-driven development**:

- Write automated tests cases for all the ways you can think of to reproduce this issue, as well as any other related code path you find that's currently not covered by the unit tests.
- Push the test cases to your PR first, so we can see that they fail with a PHP warning.
- Add your fix (again, it needs to be **minimal**) so we can see that the new test cases start passing.

More generally, it's probably not a good idea to be modifying the core low-level functions before v1.  This is also not an easy issue to understand in terms of how it can appear and why, and not an easy thing to fully fix.  If you look at those two WP tickets, the proposed patches have gradually grown to 10-20 KB in size, which is not an encouraging sign.

**Comment by nylen** [comment] 2019-02-15 01:14
I ran across something similar the other day.  From https://codex.wordpress.org/Function_Reference/get_the_excerpt:

> If this function is used outside The Loop and the post doesn't have a custom excerpt, this function will use `wp_trim_excerpt()` to generate an excerpt. That function uses `get_the_content()`, which must be used with The Loop and will cause problems if `get_the_excerpt()` is being used outside The Loop. In order to avoid the issues, use `setup_postdata()` prior to calling `get_the_excerpt()` to set up the global `$post` object. 

In other words - good luck untangling this mess.  As can be seen from the patches on the corresponding WP ticket, it runs pretty deep.

I ended up doing this, knowing that no later code cares about the contents of the `$post` variable:

```
setup_postdata( $GLOBALS['post'] =& $post_item );
$excerpt = get_the_excerpt( $post_item );
```

Source for this wonderful hack: [`setup_postdata` docs](https://codex.wordpress.org/Function_Reference/setup_postdata).

**Comment by nylen** [comment] 2019-02-15 01:52
Oops, I didn't mean to close this issue, it's a pretty nasty one but it's still valid.

**Comment by nylen** [comment] 2019-02-16 22:22
> I ended up doing this, **knowing that no later code cares about the contents of the `$post` variable**:

And it turns out that thing I knew there was totally wrong, don't do what I did above :joy:

**Comment by KTS915** [comment] 2021-11-20 19:51
Fixed by https://github.com/ClassicPress/ClassicPress/pull/521, which has been merged, so this issue can now be closed.

**Comment by bahiirwa** [comment] 2021-11-21 07:55
Thank you for this Tim.

**Closed by bahiirwa** 2021-11-21 07:55 UTC
Labels: help wanted, needs tests
