### ISSUE TITLE
🐞 CP tells plugins that it supports blocks when it shouldn't

### ISSUE THREAD

**Issue by MarcoZehe** [ClassicPress/ClassicPress#1598] opened 2024-10-18 06:53 UTC
### Expected behavior

I use ClassicPress 2.2 with the ActivityPub plugin version 3.3.3. While the UI of the plugin works fine, federation doesn't. I expect federation to just work and my user name to be found by Mastodon and other fediverse clients.

### Current behavior

However, my user name, or any of my blog posts, cannot be found from the fediverse.

When I try to query my user name from browser.pub, the server throws an error 500. In the PHP error log, I see things like:

```
"[18-Oct-2024 06:12:44 UTC] PHP Fatal error:  Uncaught Error: Call to undefined function do_blocks() in ..../wp-content/plugins/activitypub/includes/collection/class-extra-fields.php:59"
```

However, the [plugin source code](https://github.com/Automattic/wordpress-activitypub/blob/7ca9a581c43027b230ae5bc883e38f39617e1b1b/includes/collection/class-extra-fields.php#L58) clearly shows that it checks whether the installed WordPress/ClassicPress instance supports blocks or not. So, for some reason, ClassicPress tells the plugin that blocks are supported when they are clearly not.

### Possible solution

The solution is to find where ClassicPress still wrongly tells plugins that it supports blocks, and fix the wrong claim.

### Steps to reproduce bug

1. Install the ActivityPub plugin from the WordPress plugin repository.
2. Make sure you have the user name set correctly or to your liking, then try to find it from another fediverse instance like mastodon.social, or wherever you access the fediverse.
3. Watch your server's PHP error logs.

### Context

I would like to make my blog part of the fediverse. this worked in CP 2.0 and even 2.1 I think, but no longer does in 2.2.

### ClassicPress version

2.2

### PHP version

8.1

### Can you help?

I can help test a solution

**Comment by xxsimoxx** [comment] 2024-10-18 07:12
In ClassicPress 2 there are some polyfills for block related functions.

The plugin checks `$wp_version < 5.9` (CP 2 reports as WP 6.2) and `function_exists( 'register_block_type_from_metadata' )`  (CP has a polyfill for that function).

You can try setting "Blocks Compatibility" to "off", in Settings -> General but this can create problems with other plugins or themes.

The best way to fix the issue is to put this code inside an utility plugin or theme:
`add_filter( 'activitypub_site_supports_blocks', __return_false() );`

**Comment by MarcoZehe** [comment] 2024-10-18 07:39
@xxsimoxx I tried that, but if I put it anywhere in function.php in the CP TwentySeventeen child theme of my blog, for example at the very end, I get a 500 error on reload. So, somehow that line is not being liked by PHP. I copied it exactly as you wrote it.

**Comment by xxsimoxx** [comment] 2024-10-18 07:44
My bad! Sorry, the right filter is:
`add_filter( 'activitypub_site_supports_blocks', '__return_false' );`

**Comment by MarcoZehe** [comment] 2024-10-18 08:05
Thanks, this worked. However, this is far from an obvious solution, so things like this should definitely be guarded. I know that @pfefferle [guarded](https://github.com/Automattic/wordpress-activitypub/commit/cfb6345ffdcca0a94f8818d89e2910fcaf553647) against this in his plugin for the next update, but other plugins may cause similar problems in the future.

**Comment by xxsimoxx** [comment] 2024-10-18 08:16
For me it is a delicate balance.
Authors that want to support ClassicPress should use `function_exists( 'classicpress_version' )`.
It's good that ActivityPub added a filter to let users choose.

**Comment by kun18911** [comment] 2024-10-25 00:16
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.

**Comment by mattyrob** [comment] 2024-11-07 16:20
> My bad! Sorry, the right filter is: `add_filter( 'activitypub_site_supports_blocks', '__return_false' );`

Discussed at core meeting. Closing as issue resolved with above code. Can be reopened if there is more detail to share.

**Closed by mattyrob** 2024-11-07 16:20 UTC

**Comment by KTS915** [comment] 2024-11-07 16:44
It's also possible to turn off CP's polyfilling compatibility by going to `Settings`, scrolling down to somewhere near the bottom, switching `Blocks Compatibility` to `Off`, and then hitting `Save Changes`.
