### ISSUE TITLE
Missing Information: Working with JS and CSS files.

### ISSUE THREAD

**Issue by bahiirwa** [ClassicPress/ClassicPress#1093] opened 2022-08-22 07:56 UTC
We need to add Instructions to the `contributions.md` file to help with JS and CSS file contributions.
Right now we might not be using modern tools like SASS/SCSS but we need to document this for the future:
- how we use NPM and its dependencies.
- Is this locally used?
- When do we use `npm install` locally?

**Comment by viktorix** [comment] 2022-08-22 18:05
For Windows users, it should be mentioned it's not possible to run `grunt` right now - including if installing it inside WSL. I haven't been able to get grunt to work. The problem is described in issue #854

**Comment by xxsimoxx** [comment] 2024-06-20 15:02
Closing as completed by #1460.

**Closed by xxsimoxx** 2024-06-20 15:02 UTC
Labels: status: discussion, task: documentation
